### ISSUE TITLE
Parametrização do ambiente de teste

### ISSUE THREAD

**Issue by sergiocharpineljr** [lucasdiedrich/agatha#6]
Para configurar o ambiente de teste é necessário alterar os parâmetros abaixo no arquivo application.yam:
access-token-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/token
user-authorization-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/authorize

Porém, se realizarmos a alteração manual, ao subir o container esse arquivo é alterado para o parâmetro de produção, mesmo com a variável de ambiente ECIDADAO_ENV: TESTE.

**Comment by lucasdiedrich** [comment]
@sergiocharpineljr , reinicie seu container e me mande o retorno do comando a seguir:
```bash
docker exec -it <nome_do_conteiner> env
```
Acontece o seguinte, como pode ser [visto neste arquivo](https://github.com/lucasdiedrich/agatha/blob/master/files/usr/bin/pre-init#L48), se você iniciou a variável de ambiente com qualquer valor que não seja a default "**PROD**" ele ajustará o ambiente para teste. Lembrando que não adianta alterar as variáveis de ambiente depois que o container for inicializado foi a cada inicialização o docker vai rever sua configuração inicial.

**Comment by sergiocharpineljr** [comment]
Aparentemente ele não está ajustando para a URI do ambiente de teste.

:~/agatha$ sudo docker exec -it f206083d9d24 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
HOSTNAME=f206083d9d24
TERM=xterm
DB_HOST=agathadb
DB_PASSWORD=xxxx
DB_USER=xxxx
DB_NAME=agatha
DB_CHECK=1
CONF_CHECK=1
ECIDADAO_ENV=TESTE
ECIDADAO_SERVER=xxxx
ECIDADAO_ID=xxxx
ECIDADAO_SECRET=xxxx
SIORG=2981
LANG=C.UTF-8
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
JAVA_VERSION=8u171
JAVA_ALPINE_VERSION=8.171.11-r0
JAVA_OPTS=-server -Xmx2G -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70
HOME=/root

:~/agatha$ sudo docker exec -it f206083d9d24 cat /config/application.yaml
ecidadao:
...
# URIS dO AMBIENTE DE TESTES
access-token-uri: https://scp.brasilcidadao.gov.br/scp/token
user-authorization-uri: https://scp.brasilcidadao.gov.br/scp/authorize

**Comment by lucasdiedrich** [comment]
@sergiocharpineljr, consegue mandar as opções utilizadas na inicialização do container? os parâmetros utilizados?

Tente executar o script na mão e passe o retorno para nós: 
```bash
docker exec -it <container_name> /usr/bin/pre-init
```

**Comment by sergiocharpineljr** [comment]
Estou usando este docker-compose.yml 
[docker-compose.txt](https://github.com/lucasdiedrich/agatha/files/2345709/docker-compose.txt)

Saída do comando solicitado:
$ sudo docker exec -it 9 /usr/bin/pre-init
Verificando banco de dados...
NOTICE:  schema "gestaoriscos" already exists, skipping
CREATE SCHEMA
NOTICE:  schema "aud_gestaoriscos" already exists, skipping
CREATE SCHEMA
ALTER ROLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 3 more
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat servlet container
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:165)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at br.gov.mpog.gestaoriscos.SistemaApplication.main(SistemaApplication.java:38)
        ... 8 more
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:159)
        ... 18 more

**Comment by sergiocharpineljr** [comment]
Pegou a URL correta agora, obrigado!

Estou com um outro erro, que após a autenticação utilizando os CPFs de teste fornecidos recebo a mensagem Erro: invalid_grant. Pela mensagem, deve ser um erro do servidor ou da liberação. Se não tiver relação com este repositório pode encerrar.

**Comment by lucasdiedrich** [comment]
Acho que não tem erro com o docker, se você já inseriu este usuário no seu agatha [utilizando comando disponibilizado](https://github.com/lucasdiedrich/agatha#criando-usu%C3%A1rio-admin)?

Pode ser se que sejam alguma falta de liberação no BrasilCidadão...

Qualquer dúvida estou a disposição.
